### PR TITLE
Authmodule refactor

### PR DESCRIPTION
**Pull request by awichera**
Moves user creds from redux store to browser local storage.

### CODE REVIEW

**Comment by PremyslCerny** [comment]
Nice improvement

**Comment by ateska** [comment]
I was actually thinking why we do popup ... instead of a full-screen login (redirect & callback URL).
Any feedback here? @awichera @PremyslCerny

**Comment by awichera** [comment]
Well, to be honest,  I don't know, but it feels very customary with oAuth.
Almost everywhere where I encounter oAuth, it is a pop-up.

For me as a user, it kind of feels like it is a separate thing - I am not providing my password to resource owener, but I am communicating directly with auth server.

But, thats very.. behavioral reason, to be sure.

**Comment by ateska** [comment]
Well, I actually met few sites that does page-transition instead of pop-up.
The main reason for this topic is how we will support login via Google/GitHub etc. ... and this is exploratory question - if we can do that in popup seamlessly, I'm fine with that answer.

**Comment by awichera** [comment]
Yeah, we do that in pupup quite seamlessly. in my opinion - well, with GitHub. We don't have GoogleAuthMethod yet.

**Comment by ateska** [comment]
Ok. I would like to see that ... eventually.
Re. my work on SeaCat Auth now.

**Comment by ateska** [comment]
Review is done from my side (FYI).

**Comment by awichera** [comment]
By the way these are some follow up tasks I came up with:
- fix seacat-auth - 500 internal when trying to add user

- improve asab auth module - `/identity` should not reply with 200 if it got 401 from auth provider (Github)
- update TeskalabsAuthMethod - use Github auth as template
- update LDAP Auth Method - use Github auth as template
- ? create wrapper around authorized axios request, that would handle tokens, unauthorized errors and such, to not repeat this functionality with every specific request?

**Comment by ateska** [comment]
I work on a very significant refactoring of SeaCat Auth ... many of above point will become irrelevant. I suggest to reiterate once merged.

**Comment by awichera** [comment]
Sounds like a plan.

**Pull request merged**
